### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by Samkit-shah** [Samkit-shah/mysitemanager#2]
Update UI for:
Landing page
Login page
Registration page

**Comment by NinjaLabs-Dev** [comment]
What are you wanting to update about them? Got any designs in mind, examples?

**Comment by Samkit-shah** [comment]
@NinjaLabs-Dev ,
Basically using different fonts, good color combinations and buttons..
I just wish to have updated ui for registration, login  and landing page for now..
Any good ui works its should not be the basic that is pre built with laravel. 
If that us best I'll merge it or if properly implied I'll mark it approved.

**Comment by varunpusarla** [comment]
Hey, I'd like to contribute. Could you assign this to me ?

**Comment by NinjaLabs-Dev** [comment]
@Samkit-shah Ok, sounds good. I'll take a look 😄

**Comment by Samkit-shah** [comment]
@varunpusarla @NinjaLabs-Dev  sure,
Go ahead

**Comment by NinjaLabs-Dev** [comment]
Sadly I'm going to be able to do this. I'll leave it to varunpusarla's hands
